ALTER TABLE orders
ADD COLUMN subtotal DECIMAL(15, 2) NOT NULL DEFAULT 0,
ADD COLUMN discount_amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
ADD COLUMN tax_ppn DECIMAL(15, 2) NOT NULL DEFAULT 0,
ADD COLUMN tax_pph DECIMAL(15, 2) NOT NULL DEFAULT 0;