-- Tambahkan kolom pajak dan kalkulasi pengadaan instansi
ALTER TABLE orders
ADD COLUMN is_taxable BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN tax_ppn_rate NUMERIC(5, 2) NOT NULL DEFAULT 12.00,
ADD COLUMN tax_pph22_rate NUMERIC(5, 2) NOT NULL DEFAULT 1.50,
ADD COLUMN dpp_ppn NUMERIC(15, 2) NOT NULL DEFAULT 0,
ADD COLUMN dpp_pph NUMERIC(15, 2) NOT NULL DEFAULT 0,
ADD COLUMN pagu_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
ADD COLUMN net_received_amount NUMERIC(15, 2) NOT NULL DEFAULT 0;