// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AttendanceRepository is an autogenerated mock type for the AttendanceRepository type
type AttendanceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, att
func (_m *AttendanceRepository) Create(ctx context.Context, att *domain.Attendance) error {
	ret := _m.Called(ctx, att)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Attendance) error); ok {
		r0 = rf(ctx, att)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatch provides a mock function with given fields: ctx, attendances
func (_m *AttendanceRepository) CreateBatch(ctx context.Context, attendances []domain.Attendance) error {
	ret := _m.Called(ctx, attendances)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Attendance) error); ok {
		r0 = rf(ctx, attendances)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AttendanceRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, filter, limit, offset
func (_m *AttendanceRepository) Fetch(ctx context.Context, filter domain.AttendanceFilter, limit int, offset int) ([]domain.Attendance, int64, error) {
	ret := _m.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Attendance
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AttendanceFilter, int, int) ([]domain.Attendance, int64, error)); ok {
		return rf(ctx, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AttendanceFilter, int, int) []domain.Attendance); ok {
		r0 = rf(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AttendanceFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.AttendanceFilter, int, int) error); ok {
		r2 = rf(ctx, filter, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AttendanceRepository) GetByID(ctx context.Context, id string) (*domain.Attendance, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Attendance, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Attendance); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByWorkerAndDate provides a mock function with given fields: ctx, workerID, date
func (_m *AttendanceRepository) GetByWorkerAndDate(ctx context.Context, workerID string, date time.Time) (*domain.Attendance, error) {
	ret := _m.Called(ctx, workerID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetByWorkerAndDate")
	}

	var r0 *domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.Attendance, error)); ok {
		return rf(ctx, workerID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.Attendance); ok {
		r0 = rf(ctx, workerID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, workerID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalAmountByWorkerAndPeriod provides a mock function with given fields: ctx, workerID, startDate, endDate
func (_m *AttendanceRepository) GetTotalAmountByWorkerAndPeriod(ctx context.Context, workerID string, startDate time.Time, endDate time.Time) (float64, int, error) {
	ret := _m.Called(ctx, workerID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalAmountByWorkerAndPeriod")
	}

	var r0 float64
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (float64, int, error)); ok {
		return rf(ctx, workerID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, workerID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) int); ok {
		r1 = rf(ctx, workerID, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, time.Time, time.Time) error); ok {
		r2 = rf(ctx, workerID, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, att
func (_m *AttendanceRepository) Update(ctx context.Context, att *domain.Attendance) error {
	ret := _m.Called(ctx, att)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Attendance) error); ok {
		r0 = rf(ctx, att)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAttendanceRepository creates a new instance of AttendanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttendanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttendanceRepository {
	mock := &AttendanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
