// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AttendanceUsecase is an autogenerated mock type for the AttendanceUsecase type
type AttendanceUsecase struct {
	mock.Mock
}

// DeleteAttendance provides a mock function with given fields: ctx, id
func (_m *AttendanceUsecase) DeleteAttendance(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttendance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAttendance provides a mock function with given fields: ctx, id
func (_m *AttendanceUsecase) GetAttendance(ctx context.Context, id string) (*domain.Attendance, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendance")
	}

	var r0 *domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Attendance, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Attendance); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAttendances provides a mock function with given fields: ctx, query, filter
func (_m *AttendanceUsecase) ListAttendances(ctx context.Context, query domain.PaginationQuery, filter domain.AttendanceFilter) ([]domain.Attendance, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, query, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListAttendances")
	}

	var r0 []domain.Attendance
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.AttendanceFilter) ([]domain.Attendance, domain.PaginationMeta, error)); ok {
		return rf(ctx, query, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.AttendanceFilter) []domain.Attendance); ok {
		r0 = rf(ctx, query, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery, domain.AttendanceFilter) domain.PaginationMeta); ok {
		r1 = rf(ctx, query, filter)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery, domain.AttendanceFilter) error); ok {
		r2 = rf(ctx, query, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RecordAttendance provides a mock function with given fields: ctx, input
func (_m *AttendanceUsecase) RecordAttendance(ctx context.Context, input domain.AttendanceCreateInput) (*domain.Attendance, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RecordAttendance")
	}

	var r0 *domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AttendanceCreateInput) (*domain.Attendance, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AttendanceCreateInput) *domain.Attendance); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AttendanceCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordBatchAttendance provides a mock function with given fields: ctx, input
func (_m *AttendanceUsecase) RecordBatchAttendance(ctx context.Context, input domain.BatchAttendanceInput) ([]domain.Attendance, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RecordBatchAttendance")
	}

	var r0 []domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BatchAttendanceInput) ([]domain.Attendance, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BatchAttendanceInput) []domain.Attendance); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BatchAttendanceInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAttendance provides a mock function with given fields: ctx, id, input
func (_m *AttendanceUsecase) UpdateAttendance(ctx context.Context, id string, input domain.AttendanceUpdateInput) (*domain.Attendance, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttendance")
	}

	var r0 *domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AttendanceUpdateInput) (*domain.Attendance, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AttendanceUpdateInput) *domain.Attendance); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.AttendanceUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAttendanceUsecase creates a new instance of AttendanceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttendanceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttendanceUsecase {
	mock := &AttendanceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
