// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// CreateAuth provides a mock function with given fields: auth
func (_m *AuthRepository) CreateAuth(auth *domain.Auth) error {
	ret := _m.Called(auth)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Auth) error); ok {
		r0 = rf(auth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAuthByUsername provides a mock function with given fields: username
func (_m *AuthRepository) GetAuthByUsername(username string) (*domain.Auth, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthByUsername")
	}

	var r0 *domain.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Auth, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Auth); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
