// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BankAccountUsecase is an autogenerated mock type for the BankAccountUsecase type
type BankAccountUsecase struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: ctx, input
func (_m *BankAccountUsecase) CreateAccount(ctx context.Context, input domain.BankAccountCreateInput) (*domain.BankAccount, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *domain.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BankAccountCreateInput) (*domain.BankAccount, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BankAccountCreateInput) *domain.BankAccount); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BankAccountCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAccount provides a mock function with given fields: ctx, id
func (_m *BankAccountUsecase) DeleteAccount(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *BankAccountUsecase) GetAccount(ctx context.Context, id string) (*domain.BankAccount, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *domain.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.BankAccount, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.BankAccount); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGlobalAccounts provides a mock function with given fields: c
func (_m *BankAccountUsecase) GetGlobalAccounts(c context.Context) ([]domain.BankAccount, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalAccounts")
	}

	var r0 []domain.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BankAccount, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BankAccount); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAccounts provides a mock function with given fields: c, userID
func (_m *BankAccountUsecase) GetUserAccounts(c context.Context, userID string) ([]domain.BankAccount, error) {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAccounts")
	}

	var r0 []domain.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.BankAccount, error)); ok {
		return rf(c, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.BankAccount); ok {
		r0 = rf(c, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAccounts provides a mock function with given fields: c, query
func (_m *BankAccountUsecase) ListAccounts(c context.Context, query domain.PaginationQuery) ([]domain.BankAccount, domain.PaginationMeta, error) {
	ret := _m.Called(c, query)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []domain.BankAccount
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) ([]domain.BankAccount, domain.PaginationMeta, error)); ok {
		return rf(c, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) []domain.BankAccount); ok {
		r0 = rf(c, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery) domain.PaginationMeta); ok {
		r1 = rf(c, query)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery) error); ok {
		r2 = rf(c, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateAccount provides a mock function with given fields: ctx, id, input
func (_m *BankAccountUsecase) UpdateAccount(ctx context.Context, id string, input domain.BankAccountUpdateInput) (*domain.BankAccount, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 *domain.BankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BankAccountUpdateInput) (*domain.BankAccount, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BankAccountUpdateInput) *domain.BankAccount); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.BankAccountUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBankAccountUsecase creates a new instance of BankAccountUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBankAccountUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BankAccountUsecase {
	mock := &BankAccountUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
