// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BatchPOUsecase is an autogenerated mock type for the BatchPOUsecase type
type BatchPOUsecase struct {
	mock.Mock
}

// CreateBatchPO provides a mock function with given fields: ctx, input
func (_m *BatchPOUsecase) CreateBatchPO(ctx context.Context, input domain.BatchPOCreateInput) (*domain.BatchPO, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchPO")
	}

	var r0 *domain.BatchPO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BatchPOCreateInput) (*domain.BatchPO, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BatchPOCreateInput) *domain.BatchPO); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BatchPOCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBatchPO provides a mock function with given fields: ctx, id
func (_m *BatchPOUsecase) DeleteBatchPO(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatchPO")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBatchPO provides a mock function with given fields: ctx, id
func (_m *BatchPOUsecase) GetBatchPO(ctx context.Context, id string) (*domain.BatchPO, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchPO")
	}

	var r0 *domain.BatchPO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.BatchPO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.BatchPO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSuggestedOpenDate provides a mock function with given fields: ctx
func (_m *BatchPOUsecase) GetSuggestedOpenDate(ctx context.Context) (*time.Time, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSuggestedOpenDate")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*time.Time, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *time.Time); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListActiveBatchPOs provides a mock function with given fields: ctx
func (_m *BatchPOUsecase) ListActiveBatchPOs(ctx context.Context) ([]domain.BatchPO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveBatchPOs")
	}

	var r0 []domain.BatchPO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BatchPO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BatchPO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBatchPOs provides a mock function with given fields: ctx, query
func (_m *BatchPOUsecase) ListBatchPOs(ctx context.Context, query domain.PaginationQuery) ([]domain.BatchPO, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListBatchPOs")
	}

	var r0 []domain.BatchPO
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) ([]domain.BatchPO, domain.PaginationMeta, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) []domain.BatchPO); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery) domain.PaginationMeta); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateBatchPO provides a mock function with given fields: ctx, id, input
func (_m *BatchPOUsecase) UpdateBatchPO(ctx context.Context, id string, input domain.BatchPOUpdateInput) (*domain.BatchPO, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatchPO")
	}

	var r0 *domain.BatchPO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BatchPOUpdateInput) (*domain.BatchPO, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BatchPOUpdateInput) *domain.BatchPO); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.BatchPOUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *BatchPOUsecase) UpdateStatus(ctx context.Context, id string, status domain.BatchPOStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.BatchPOStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBatchPOUsecase creates a new instance of BatchPOUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchPOUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchPOUsecase {
	mock := &BatchPOUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
