// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BatchPORepository is an autogenerated mock type for the BatchPORepository type
type BatchPORepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, batchPO
func (_m *BatchPORepository) Create(ctx context.Context, batchPO *domain.BatchPO) error {
	ret := _m.Called(ctx, batchPO)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BatchPO) error); ok {
		r0 = rf(ctx, batchPO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BatchPORepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, limit, offset
func (_m *BatchPORepository) Fetch(ctx context.Context, limit int, offset int) ([]domain.BatchPO, int64, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.BatchPO
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.BatchPO, int64, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []domain.BatchPO); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FetchActive provides a mock function with given fields: ctx
func (_m *BatchPORepository) FetchActive(ctx context.Context) ([]domain.BatchPO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchActive")
	}

	var r0 []domain.BatchPO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BatchPO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BatchPO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchLatest provides a mock function with given fields: ctx
func (_m *BatchPORepository) FetchLatest(ctx context.Context) (*domain.BatchPO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchLatest")
	}

	var r0 *domain.BatchPO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.BatchPO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.BatchPO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActivePOByDate provides a mock function with given fields: ctx, targetDate
func (_m *BatchPORepository) GetActivePOByDate(ctx context.Context, targetDate time.Time) (*domain.BatchPO, error) {
	ret := _m.Called(ctx, targetDate)

	if len(ret) == 0 {
		panic("no return value specified for GetActivePOByDate")
	}

	var r0 *domain.BatchPO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*domain.BatchPO, error)); ok {
		return rf(ctx, targetDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *domain.BatchPO); ok {
		r0 = rf(ctx, targetDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, targetDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BatchPORepository) GetByID(ctx context.Context, id string) (*domain.BatchPO, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.BatchPO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.BatchPO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.BatchPO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BatchPO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, batchPO
func (_m *BatchPORepository) Update(ctx context.Context, batchPO *domain.BatchPO) error {
	ret := _m.Called(ctx, batchPO)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BatchPO) error); ok {
		r0 = rf(ctx, batchPO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBatchPORepository creates a new instance of BatchPORepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchPORepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchPORepository {
	mock := &BatchPORepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
