// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CategoryUsecase is an autogenerated mock type for the CategoryUsecase type
type CategoryUsecase struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, input
func (_m *CategoryUsecase) CreateCategory(ctx context.Context, input domain.CategoryCreateInput) (*domain.Category, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CategoryCreateInput) (*domain.Category, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CategoryCreateInput) *domain.Category); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CategoryCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCategory provides a mock function with given fields: ctx, id
func (_m *CategoryUsecase) DeleteCategory(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCategory provides a mock function with given fields: ctx, id
func (_m *CategoryUsecase) GetCategory(ctx context.Context, id string) (*domain.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCategories provides a mock function with given fields: c, query
func (_m *CategoryUsecase) ListCategories(c context.Context, query domain.PaginationQuery) ([]domain.Category, domain.PaginationMeta, error) {
	ret := _m.Called(c, query)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []domain.Category
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) ([]domain.Category, domain.PaginationMeta, error)); ok {
		return rf(c, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) []domain.Category); ok {
		r0 = rf(c, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery) domain.PaginationMeta); ok {
		r1 = rf(c, query)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery) error); ok {
		r2 = rf(c, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateCategory provides a mock function with given fields: ctx, id, input
func (_m *CategoryUsecase) UpdateCategory(ctx context.Context, id string, input domain.CategoryUpdateInput) (*domain.Category, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CategoryUpdateInput) (*domain.Category, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CategoryUpdateInput) *domain.Category); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.CategoryUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoryUsecase creates a new instance of CategoryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryUsecase {
	mock := &CategoryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
