// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CustomerUsecase is an autogenerated mock type for the CustomerUsecase type
type CustomerUsecase struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: ctx, input
func (_m *CustomerUsecase) CreateCustomer(ctx context.Context, input domain.CustomerCreateInput) (*domain.Customer, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CustomerCreateInput) (*domain.Customer, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CustomerCreateInput) *domain.Customer); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CustomerCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCustomer provides a mock function with given fields: ctx, id
func (_m *CustomerUsecase) DeleteCustomer(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCustomer provides a mock function with given fields: ctx, id, operatorID, operatorRole
func (_m *CustomerUsecase) GetCustomer(ctx context.Context, id string, operatorID string, operatorRole domain.Role) (*domain.Customer, error) {
	ret := _m.Called(ctx, id, operatorID, operatorRole)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomer")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.Role) (*domain.Customer, error)); ok {
		return rf(ctx, id, operatorID, operatorRole)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.Role) *domain.Customer); ok {
		r0 = rf(ctx, id, operatorID, operatorRole)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.Role) error); ok {
		r1 = rf(ctx, id, operatorID, operatorRole)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCustomers provides a mock function with given fields: ctx, query, filter, operatorID, operatorRole
func (_m *CustomerUsecase) ListCustomers(ctx context.Context, query domain.PaginationQuery, filter domain.CustomerFilter, operatorID string, operatorRole domain.Role) ([]domain.Customer, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, query, filter, operatorID, operatorRole)

	if len(ret) == 0 {
		panic("no return value specified for ListCustomers")
	}

	var r0 []domain.Customer
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.CustomerFilter, string, domain.Role) ([]domain.Customer, domain.PaginationMeta, error)); ok {
		return rf(ctx, query, filter, operatorID, operatorRole)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.CustomerFilter, string, domain.Role) []domain.Customer); ok {
		r0 = rf(ctx, query, filter, operatorID, operatorRole)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery, domain.CustomerFilter, string, domain.Role) domain.PaginationMeta); ok {
		r1 = rf(ctx, query, filter, operatorID, operatorRole)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery, domain.CustomerFilter, string, domain.Role) error); ok {
		r2 = rf(ctx, query, filter, operatorID, operatorRole)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateCustomer provides a mock function with given fields: ctx, id, input
func (_m *CustomerUsecase) UpdateCustomer(ctx context.Context, id string, input domain.CustomerUpdateInput) (*domain.Customer, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomer")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CustomerUpdateInput) (*domain.Customer, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.CustomerUpdateInput) *domain.Customer); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.CustomerUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerUsecase creates a new instance of CustomerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerUsecase {
	mock := &CustomerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
