// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// DashboardUsecase is an autogenerated mock type for the DashboardUsecase type
type DashboardUsecase struct {
	mock.Mock
}

// GetSummary provides a mock function with given fields: ctx, filter
func (_m *DashboardUsecase) GetSummary(ctx context.Context, filter domain.DashboardFilter) (*domain.DashboardSummary, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 *domain.DashboardSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.DashboardFilter) (*domain.DashboardSummary, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.DashboardFilter) *domain.DashboardSummary); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DashboardSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.DashboardFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDashboardUsecase creates a new instance of DashboardUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardUsecase {
	mock := &DashboardUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
