// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ExpenseUsecase is an autogenerated mock type for the ExpenseUsecase type
type ExpenseUsecase struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, input
func (_m *ExpenseUsecase) CreateCategory(ctx context.Context, input domain.ExpenseCategoryCreateInput) (*domain.ExpenseCategory, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *domain.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExpenseCategoryCreateInput) (*domain.ExpenseCategory, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExpenseCategoryCreateInput) *domain.ExpenseCategory); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ExpenseCategoryCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateExpense provides a mock function with given fields: ctx, input
func (_m *ExpenseUsecase) CreateExpense(ctx context.Context, input domain.ExpenseCreateInput) (*domain.Expense, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateExpense")
	}

	var r0 *domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExpenseCreateInput) (*domain.Expense, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExpenseCreateInput) *domain.Expense); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ExpenseCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteExpense provides a mock function with given fields: ctx, id
func (_m *ExpenseUsecase) DeleteExpense(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExpense provides a mock function with given fields: ctx, id
func (_m *ExpenseUsecase) GetExpense(ctx context.Context, id string) (*domain.Expense, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetExpense")
	}

	var r0 *domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Expense, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Expense); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCategories provides a mock function with given fields: ctx
func (_m *ExpenseUsecase) ListCategories(ctx context.Context) ([]domain.ExpenseCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []domain.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ExpenseCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ExpenseCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListExpenses provides a mock function with given fields: ctx, query, poID, startDate, endDate
func (_m *ExpenseUsecase) ListExpenses(ctx context.Context, query domain.PaginationQuery, poID *string, startDate *string, endDate *string) ([]domain.Expense, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, query, poID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for ListExpenses")
	}

	var r0 []domain.Expense
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, *string, *string, *string) ([]domain.Expense, domain.PaginationMeta, error)); ok {
		return rf(ctx, query, poID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, *string, *string, *string) []domain.Expense); ok {
		r0 = rf(ctx, query, poID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery, *string, *string, *string) domain.PaginationMeta); ok {
		r1 = rf(ctx, query, poID, startDate, endDate)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery, *string, *string, *string) error); ok {
		r2 = rf(ctx, query, poID, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewExpenseUsecase creates a new instance of ExpenseUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseUsecase {
	mock := &ExpenseUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
