// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type ExpenseRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, expense
func (_m *ExpenseRepository) Create(ctx context.Context, expense *domain.Expense) error {
	ret := _m.Called(ctx, expense)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Expense) error); ok {
		r0 = rf(ctx, expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCategory provides a mock function with given fields: ctx, category
func (_m *ExpenseRepository) CreateCategory(ctx context.Context, category *domain.ExpenseCategory) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ExpenseCategory) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ExpenseRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, limit, offset, poID, startDate, endDate
func (_m *ExpenseRepository) Fetch(ctx context.Context, limit int, offset int, poID *string, startDate *time.Time, endDate *time.Time) ([]domain.Expense, int64, error) {
	ret := _m.Called(ctx, limit, offset, poID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Expense
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *string, *time.Time, *time.Time) ([]domain.Expense, int64, error)); ok {
		return rf(ctx, limit, offset, poID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *string, *time.Time, *time.Time) []domain.Expense); ok {
		r0 = rf(ctx, limit, offset, poID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *string, *time.Time, *time.Time) int64); ok {
		r1 = rf(ctx, limit, offset, poID, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, *string, *time.Time, *time.Time) error); ok {
		r2 = rf(ctx, limit, offset, poID, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FetchCategories provides a mock function with given fields: ctx
func (_m *ExpenseRepository) FetchCategories(ctx context.Context) ([]domain.ExpenseCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchCategories")
	}

	var r0 []domain.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ExpenseCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ExpenseCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ExpenseRepository) GetByID(ctx context.Context, id string) (*domain.Expense, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Expense
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Expense, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Expense); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExpenseRepository creates a new instance of ExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseRepository {
	mock := &ExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
