// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MaterialUsecase is an autogenerated mock type for the MaterialUsecase type
type MaterialUsecase struct {
	mock.Mock
}

// CreateMaterial provides a mock function with given fields: ctx, input
func (_m *MaterialUsecase) CreateMaterial(ctx context.Context, input domain.MaterialCreateInput) (*domain.Material, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateMaterial")
	}

	var r0 *domain.Material
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MaterialCreateInput) (*domain.Material, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MaterialCreateInput) *domain.Material); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Material)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MaterialCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMaterial provides a mock function with given fields: ctx, id
func (_m *MaterialUsecase) DeleteMaterial(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMaterial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMaterial provides a mock function with given fields: ctx, id
func (_m *MaterialUsecase) GetMaterial(ctx context.Context, id string) (*domain.Material, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMaterial")
	}

	var r0 *domain.Material
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Material, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Material); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Material)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMaterials provides a mock function with given fields: ctx, query
func (_m *MaterialUsecase) ListMaterials(ctx context.Context, query domain.PaginationQuery) ([]domain.Material, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListMaterials")
	}

	var r0 []domain.Material
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) ([]domain.Material, domain.PaginationMeta, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) []domain.Material); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Material)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery) domain.PaginationMeta); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateMaterial provides a mock function with given fields: ctx, id, input
func (_m *MaterialUsecase) UpdateMaterial(ctx context.Context, id string, input domain.MaterialUpdateInput) (*domain.Material, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMaterial")
	}

	var r0 *domain.Material
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MaterialUpdateInput) (*domain.Material, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MaterialUpdateInput) *domain.Material); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Material)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.MaterialUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMaterialUsecase creates a new instance of MaterialUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaterialUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MaterialUsecase {
	mock := &MaterialUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
