// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderUsecase is an autogenerated mock type for the OrderUsecase type
type OrderUsecase struct {
	mock.Mock
}

// AddOrderItem provides a mock function with given fields: ctx, orderID, input
func (_m *OrderUsecase) AddOrderItem(ctx context.Context, orderID string, input domain.OrderItemInput) (*domain.Order, error) {
	ret := _m.Called(ctx, orderID, input)

	if len(ret) == 0 {
		panic("no return value specified for AddOrderItem")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.OrderItemInput) (*domain.Order, error)); ok {
		return rf(ctx, orderID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.OrderItemInput) *domain.Order); ok {
		r0 = rf(ctx, orderID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.OrderItemInput) error); ok {
		r1 = rf(ctx, orderID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrder provides a mock function with given fields: ctx, input
func (_m *OrderUsecase) CreateOrder(ctx context.Context, input domain.OrderCreateInput) (*domain.Order, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrderCreateInput) (*domain.Order, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrderCreateInput) *domain.Order); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.OrderCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOrder provides a mock function with given fields: ctx, id
func (_m *OrderUsecase) DeleteOrder(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOrderItem provides a mock function with given fields: ctx, orderID, itemID
func (_m *OrderUsecase) DeleteOrderItem(ctx context.Context, orderID string, itemID string) (*domain.Order, error) {
	ret := _m.Called(ctx, orderID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrderItem")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Order, error)); ok {
		return rf(ctx, orderID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Order); ok {
		r0 = rf(ctx, orderID, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orderID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *OrderUsecase) GetOrder(ctx context.Context, id string) (*domain.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrders provides a mock function with given fields: ctx, filter, query
func (_m *OrderUsecase) ListOrders(ctx context.Context, filter domain.OrderFilter, query domain.PaginationQuery) ([]domain.Order, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, filter, query)

	if len(ret) == 0 {
		panic("no return value specified for ListOrders")
	}

	var r0 []domain.Order
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrderFilter, domain.PaginationQuery) ([]domain.Order, domain.PaginationMeta, error)); ok {
		return rf(ctx, filter, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrderFilter, domain.PaginationQuery) []domain.Order); ok {
		r0 = rf(ctx, filter, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.OrderFilter, domain.PaginationQuery) domain.PaginationMeta); ok {
		r1 = rf(ctx, filter, query)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.OrderFilter, domain.PaginationQuery) error); ok {
		r2 = rf(ctx, filter, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateOrder provides a mock function with given fields: ctx, id, input
func (_m *OrderUsecase) UpdateOrder(ctx context.Context, id string, input domain.OrderUpdateInput) (*domain.Order, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.OrderUpdateInput) (*domain.Order, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.OrderUpdateInput) *domain.Order); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.OrderUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderItem provides a mock function with given fields: ctx, orderID, itemID, input
func (_m *OrderUsecase) UpdateOrderItem(ctx context.Context, orderID string, itemID string, input domain.OrderItemInput) (*domain.Order, error) {
	ret := _m.Called(ctx, orderID, itemID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderItem")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.OrderItemInput) (*domain.Order, error)); ok {
		return rf(ctx, orderID, itemID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.OrderItemInput) *domain.Order); ok {
		r0 = rf(ctx, orderID, itemID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.OrderItemInput) error); ok {
		r1 = rf(ctx, orderID, itemID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderStatus provides a mock function with given fields: ctx, id, status
func (_m *OrderUsecase) UpdateOrderStatus(ctx context.Context, id string, status domain.OrderStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.OrderStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentStatus provides a mock function with given fields: ctx, id, status
func (_m *OrderUsecase) UpdatePaymentStatus(ctx context.Context, id string, status domain.PaymentStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PaymentStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderUsecase creates a new instance of OrderUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderUsecase {
	mock := &OrderUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
