// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payment
func (_m *PaymentRepository) Create(ctx context.Context, payment *domain.Payment) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PaymentRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, limit, offset, filter
func (_m *PaymentRepository) Fetch(ctx context.Context, limit int, offset int, filter domain.PaymentFilter) ([]domain.Payment, int64, error) {
	ret := _m.Called(ctx, limit, offset, filter)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Payment
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.PaymentFilter) ([]domain.Payment, int64, error)); ok {
		return rf(ctx, limit, offset, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.PaymentFilter) []domain.Payment); ok {
		r0 = rf(ctx, limit, offset, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, domain.PaymentFilter) int64); ok {
		r1 = rf(ctx, limit, offset, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, domain.PaymentFilter) error); ok {
		r2 = rf(ctx, limit, offset, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PaymentRepository) GetByID(ctx context.Context, id string) (*domain.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByOrderID provides a mock function with given fields: ctx, orderID
func (_m *PaymentRepository) GetByOrderID(ctx context.Context, orderID string) ([]domain.Payment, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderID")
	}

	var r0 []domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Payment, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Payment); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, payment
func (_m *PaymentRepository) Update(ctx context.Context, payment *domain.Payment) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVerificationStatus provides a mock function with given fields: ctx, paymentID, status, verifiedByID, verifiedAt
func (_m *PaymentRepository) UpdateVerificationStatus(ctx context.Context, paymentID string, status domain.PaymentVerificationStatus, verifiedByID string, verifiedAt time.Time) error {
	ret := _m.Called(ctx, paymentID, status, verifiedByID, verifiedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVerificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PaymentVerificationStatus, string, time.Time) error); ok {
		r0 = rf(ctx, paymentID, status, verifiedByID, verifiedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentRepository creates a new instance of PaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepository {
	mock := &PaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
