// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PaymentUsecase is an autogenerated mock type for the PaymentUsecase type
type PaymentUsecase struct {
	mock.Mock
}

// DeletePayment provides a mock function with given fields: ctx, id
func (_m *PaymentUsecase) DeletePayment(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPayment provides a mock function with given fields: ctx, id
func (_m *PaymentUsecase) GetPayment(ctx context.Context, id string) (*domain.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPayments provides a mock function with given fields: c, query
func (_m *PaymentUsecase) ListPayments(c context.Context, query domain.PaginationQuery) ([]domain.Payment, domain.PaginationMeta, error) {
	ret := _m.Called(c, query)

	if len(ret) == 0 {
		panic("no return value specified for ListPayments")
	}

	var r0 []domain.Payment
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) ([]domain.Payment, domain.PaginationMeta, error)); ok {
		return rf(c, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) []domain.Payment); ok {
		r0 = rf(c, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery) domain.PaginationMeta); ok {
		r1 = rf(c, query)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery) error); ok {
		r2 = rf(c, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProcessPayment provides a mock function with given fields: ctx, input
func (_m *PaymentUsecase) ProcessPayment(ctx context.Context, input domain.PaymentCreateInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentCreateInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePayment provides a mock function with given fields: ctx, id, input
func (_m *PaymentUsecase) UpdatePayment(ctx context.Context, id string, input domain.PaymentUpdateInput) error {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PaymentUpdateInput) error); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentUsecase creates a new instance of PaymentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentUsecase {
	mock := &PaymentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
