// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PayrollRepository is an autogenerated mock type for the PayrollRepository type
type PayrollRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payroll, workLogIDs
func (_m *PayrollRepository) Create(ctx context.Context, payroll *domain.Payroll, workLogIDs []string) error {
	ret := _m.Called(ctx, payroll, workLogIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payroll, []string) error); ok {
		r0 = rf(ctx, payroll, workLogIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PayrollRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, filter, limit, offset
func (_m *PayrollRepository) Fetch(ctx context.Context, filter domain.PayrollFilter, limit int, offset int) ([]domain.Payroll, int64, error) {
	ret := _m.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Payroll
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PayrollFilter, int, int) ([]domain.Payroll, int64, error)); ok {
		return rf(ctx, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PayrollFilter, int, int) []domain.Payroll); ok {
		r0 = rf(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PayrollFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PayrollFilter, int, int) error); ok {
		r2 = rf(ctx, filter, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PayrollRepository) GetByID(ctx context.Context, id string) (*domain.Payroll, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payroll, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payroll); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, expenseID, paidAt
func (_m *PayrollRepository) UpdateStatus(ctx context.Context, id string, status domain.PayrollStatus, expenseID *string, paidAt *time.Time) error {
	ret := _m.Called(ctx, id, status, expenseID, paidAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PayrollStatus, *string, *time.Time) error); ok {
		r0 = rf(ctx, id, status, expenseID, paidAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPayrollRepository creates a new instance of PayrollRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayrollRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PayrollRepository {
	mock := &PayrollRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
