// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PayrollUsecase is an autogenerated mock type for the PayrollUsecase type
type PayrollUsecase struct {
	mock.Mock
}

// CreatePayroll provides a mock function with given fields: ctx, input
func (_m *PayrollUsecase) CreatePayroll(ctx context.Context, input domain.PayrollCreateInput) (*domain.Payroll, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayroll")
	}

	var r0 *domain.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PayrollCreateInput) (*domain.Payroll, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PayrollCreateInput) *domain.Payroll); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PayrollCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePayroll provides a mock function with given fields: ctx, id
func (_m *PayrollUsecase) DeletePayroll(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePayroll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPayroll provides a mock function with given fields: ctx, id
func (_m *PayrollUsecase) GetPayroll(ctx context.Context, id string) (*domain.Payroll, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPayroll")
	}

	var r0 *domain.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payroll, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payroll); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPayrolls provides a mock function with given fields: ctx, query, filter
func (_m *PayrollUsecase) ListPayrolls(ctx context.Context, query domain.PaginationQuery, filter domain.PayrollFilter) ([]domain.Payroll, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, query, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPayrolls")
	}

	var r0 []domain.Payroll
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.PayrollFilter) ([]domain.Payroll, domain.PaginationMeta, error)); ok {
		return rf(ctx, query, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.PayrollFilter) []domain.Payroll); ok {
		r0 = rf(ctx, query, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery, domain.PayrollFilter) domain.PaginationMeta); ok {
		r1 = rf(ctx, query, filter)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery, domain.PayrollFilter) error); ok {
		r2 = rf(ctx, query, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProcessPayrollPayment provides a mock function with given fields: ctx, id, operatorID
func (_m *PayrollUsecase) ProcessPayrollPayment(ctx context.Context, id string, operatorID string) (*domain.Payroll, error) {
	ret := _m.Called(ctx, id, operatorID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayrollPayment")
	}

	var r0 *domain.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Payroll, error)); ok {
		return rf(ctx, id, operatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Payroll); ok {
		r0 = rf(ctx, id, operatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, operatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPayrollUsecase creates a new instance of PayrollUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayrollUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PayrollUsecase {
	mock := &PayrollUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
