// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProductMaterialRepository is an autogenerated mock type for the ProductMaterialRepository type
type ProductMaterialRepository struct {
	mock.Mock
}

// FetchByProduct provides a mock function with given fields: ctx, productID
func (_m *ProductMaterialRepository) FetchByProduct(ctx context.Context, productID string) ([]domain.ProductMaterial, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByProduct")
	}

	var r0 []domain.ProductMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.ProductMaterial, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.ProductMaterial); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReplaceForProduct provides a mock function with given fields: ctx, productID, items
func (_m *ProductMaterialRepository) ReplaceForProduct(ctx context.Context, productID string, items []domain.ProductMaterial) error {
	ret := _m.Called(ctx, productID, items)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceForProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.ProductMaterial) error); ok {
		r0 = rf(ctx, productID, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductMaterialRepository creates a new instance of ProductMaterialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductMaterialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductMaterialRepository {
	mock := &ProductMaterialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
