// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProductMaterialUsecase is an autogenerated mock type for the ProductMaterialUsecase type
type ProductMaterialUsecase struct {
	mock.Mock
}

// CalculateMaterialCost provides a mock function with given fields: ctx, productID, qty, fabricID
func (_m *ProductMaterialUsecase) CalculateMaterialCost(ctx context.Context, productID string, qty int, fabricID ...string) (float64, error) {
	_va := make([]interface{}, len(fabricID))
	for _i := range fabricID {
		_va[_i] = fabricID[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, productID, qty)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CalculateMaterialCost")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, ...string) (float64, error)); ok {
		return rf(ctx, productID, qty, fabricID...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, ...string) float64); ok {
		r0 = rf(ctx, productID, qty, fabricID...)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, ...string) error); ok {
		r1 = rf(ctx, productID, qty, fabricID...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductMaterials provides a mock function with given fields: ctx, productID
func (_m *ProductMaterialUsecase) GetProductMaterials(ctx context.Context, productID string) ([]domain.ProductMaterial, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductMaterials")
	}

	var r0 []domain.ProductMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.ProductMaterial, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.ProductMaterial); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetProductMaterials provides a mock function with given fields: ctx, input
func (_m *ProductMaterialUsecase) SetProductMaterials(ctx context.Context, input domain.SetProductMaterialsInput) ([]domain.ProductMaterial, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SetProductMaterials")
	}

	var r0 []domain.ProductMaterial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SetProductMaterialsInput) ([]domain.ProductMaterial, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SetProductMaterialsInput) []domain.ProductMaterial); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductMaterial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SetProductMaterialsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductMaterialUsecase creates a new instance of ProductMaterialUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductMaterialUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductMaterialUsecase {
	mock := &ProductMaterialUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
