// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ReportUsecase is an autogenerated mock type for the ReportUsecase type
type ReportUsecase struct {
	mock.Mock
}

// GenerateDailyReport provides a mock function with given fields: ctx, dateStr
func (_m *ReportUsecase) GenerateDailyReport(ctx context.Context, dateStr string) (*domain.DailyReport, error) {
	ret := _m.Called(ctx, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDailyReport")
	}

	var r0 *domain.DailyReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.DailyReport, error)); ok {
		return rf(ctx, dateStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.DailyReport); ok {
		r0 = rf(ctx, dateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DailyReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dateStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDailyReport provides a mock function with given fields: ctx, date
func (_m *ReportUsecase) GetDailyReport(ctx context.Context, date string) (*domain.ReportResponse, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyReport")
	}

	var r0 *domain.ReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ReportResponse, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ReportResponse); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPOSummaryReport provides a mock function with given fields: ctx, poID
func (_m *ReportUsecase) GetPOSummaryReport(ctx context.Context, poID string) (*domain.POSummaryReport, error) {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for GetPOSummaryReport")
	}

	var r0 *domain.POSummaryReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.POSummaryReport, error)); ok {
		return rf(ctx, poID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.POSummaryReport); ok {
		r0 = rf(ctx, poID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.POSummaryReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReceivablesDetailReport provides a mock function with given fields: ctx
func (_m *ReportUsecase) GetReceivablesDetailReport(ctx context.Context) ([]domain.ReceivableDetail, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReceivablesDetailReport")
	}

	var r0 []domain.ReceivableDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ReceivableDetail, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ReceivableDetail); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReceivableDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportUsecase creates a new instance of ReportUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportUsecase {
	mock := &ReportUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
