// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ReportUsecase is an autogenerated mock type for the ReportUsecase type
type ReportUsecase struct {
	mock.Mock
}

// GetAccountingReport provides a mock function with given fields: ctx, startDate, endDate
func (_m *ReportUsecase) GetAccountingReport(ctx context.Context, startDate time.Time, endDate time.Time) (*domain.AccountingReport, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountingReport")
	}

	var r0 *domain.AccountingReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (*domain.AccountingReport, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) *domain.AccountingReport); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccountingReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPOSummaryReport provides a mock function with given fields: ctx, poID
func (_m *ReportUsecase) GetPOSummaryReport(ctx context.Context, poID string) (*domain.POSummaryReport, error) {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for GetPOSummaryReport")
	}

	var r0 *domain.POSummaryReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.POSummaryReport, error)); ok {
		return rf(ctx, poID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.POSummaryReport); ok {
		r0 = rf(ctx, poID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.POSummaryReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductionReport provides a mock function with given fields: ctx, targetMonth, targetYear
func (_m *ReportUsecase) GetProductionReport(ctx context.Context, targetMonth int, targetYear int) (*domain.ProductionReport, error) {
	ret := _m.Called(ctx, targetMonth, targetYear)

	if len(ret) == 0 {
		panic("no return value specified for GetProductionReport")
	}

	var r0 *domain.ProductionReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.ProductionReport, error)); ok {
		return rf(ctx, targetMonth, targetYear)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.ProductionReport); ok {
		r0 = rf(ctx, targetMonth, targetYear)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductionReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, targetMonth, targetYear)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReceivablesDetailReport provides a mock function with given fields: ctx
func (_m *ReportUsecase) GetReceivablesDetailReport(ctx context.Context) ([]domain.ReceivableDetail, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReceivablesDetailReport")
	}

	var r0 []domain.ReceivableDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ReceivableDetail, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ReceivableDetail); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReceivableDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportUsecase creates a new instance of ReportUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportUsecase {
	mock := &ReportUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
