// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

// GetActivePOStats provides a mock function with given fields: ctx
func (_m *ReportRepository) GetActivePOStats(ctx context.Context) ([]domain.ActivePO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActivePOStats")
	}

	var r0 []domain.ActivePO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ActivePO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ActivePO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ActivePO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDailyReportData provides a mock function with given fields: ctx, targetDate
func (_m *ReportRepository) GetDailyReportData(ctx context.Context, targetDate time.Time) (*domain.DailyReport, error) {
	ret := _m.Called(ctx, targetDate)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyReportData")
	}

	var r0 *domain.DailyReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*domain.DailyReport, error)); ok {
		return rf(ctx, targetDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *domain.DailyReport); ok {
		r0 = rf(ctx, targetDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DailyReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, targetDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDailyRevenueAndQty provides a mock function with given fields: ctx, startOfDay, endOfDay
func (_m *ReportRepository) GetDailyRevenueAndQty(ctx context.Context, startOfDay time.Time, endOfDay time.Time) (float64, int64, error) {
	ret := _m.Called(ctx, startOfDay, endOfDay)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyRevenueAndQty")
	}

	var r0 float64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (float64, int64, error)); ok {
		return rf(ctx, startOfDay, endOfDay)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, startOfDay, endOfDay)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) int64); ok {
		r1 = rf(ctx, startOfDay, endOfDay)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, time.Time, time.Time) error); ok {
		r2 = rf(ctx, startOfDay, endOfDay)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPOSummaryData provides a mock function with given fields: ctx, poID
func (_m *ReportRepository) GetPOSummaryData(ctx context.Context, poID string) (*domain.POSummaryReport, error) {
	ret := _m.Called(ctx, poID)

	if len(ret) == 0 {
		panic("no return value specified for GetPOSummaryData")
	}

	var r0 *domain.POSummaryReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.POSummaryReport, error)); ok {
		return rf(ctx, poID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.POSummaryReport); ok {
		r0 = rf(ctx, poID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.POSummaryReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, poID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPastDueReceivables provides a mock function with given fields: ctx
func (_m *ReportRepository) GetPastDueReceivables(ctx context.Context) ([]domain.PastDueReceivable, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPastDueReceivables")
	}

	var r0 []domain.PastDueReceivable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.PastDueReceivable, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.PastDueReceivable); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PastDueReceivable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReceivablesStats provides a mock function with given fields: ctx
func (_m *ReportRepository) GetReceivablesStats(ctx context.Context) (float64, float64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReceivablesStats")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (float64, float64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) float64); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSalesPerformanceByActivePO provides a mock function with given fields: ctx
func (_m *ReportRepository) GetSalesPerformanceByActivePO(ctx context.Context) ([]domain.SalesPerformanceToday, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesPerformanceByActivePO")
	}

	var r0 []domain.SalesPerformanceToday
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.SalesPerformanceToday, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.SalesPerformanceToday); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SalesPerformanceToday)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
