// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// SpecTemplateUsecase is an autogenerated mock type for the SpecTemplateUsecase type
type SpecTemplateUsecase struct {
	mock.Mock
}

// CreateSpecTemplate provides a mock function with given fields: ctx, input
func (_m *SpecTemplateUsecase) CreateSpecTemplate(ctx context.Context, input domain.SpecTemplateCreateInput) (*domain.SpecTemplate, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateSpecTemplate")
	}

	var r0 *domain.SpecTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SpecTemplateCreateInput) (*domain.SpecTemplate, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SpecTemplateCreateInput) *domain.SpecTemplate); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SpecTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SpecTemplateCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSpecTemplate provides a mock function with given fields: ctx, id
func (_m *SpecTemplateUsecase) DeleteSpecTemplate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSpecTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSpecTemplate provides a mock function with given fields: ctx, id
func (_m *SpecTemplateUsecase) GetSpecTemplate(ctx context.Context, id string) (*domain.SpecTemplate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSpecTemplate")
	}

	var r0 *domain.SpecTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.SpecTemplate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.SpecTemplate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SpecTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSpecTemplates provides a mock function with given fields: c, query
func (_m *SpecTemplateUsecase) ListSpecTemplates(c context.Context, query domain.PaginationQuery) ([]domain.SpecTemplate, domain.PaginationMeta, error) {
	ret := _m.Called(c, query)

	if len(ret) == 0 {
		panic("no return value specified for ListSpecTemplates")
	}

	var r0 []domain.SpecTemplate
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) ([]domain.SpecTemplate, domain.PaginationMeta, error)); ok {
		return rf(c, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery) []domain.SpecTemplate); ok {
		r0 = rf(c, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SpecTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery) domain.PaginationMeta); ok {
		r1 = rf(c, query)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery) error); ok {
		r2 = rf(c, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateSpecTemplate provides a mock function with given fields: ctx, id, input
func (_m *SpecTemplateUsecase) UpdateSpecTemplate(ctx context.Context, id string, input domain.SpecTemplateUpdateInput) (*domain.SpecTemplate, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSpecTemplate")
	}

	var r0 *domain.SpecTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SpecTemplateUpdateInput) (*domain.SpecTemplate, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SpecTemplateUpdateInput) *domain.SpecTemplate); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SpecTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.SpecTemplateUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSpecTemplateUsecase creates a new instance of SpecTemplateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpecTemplateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpecTemplateUsecase {
	mock := &SpecTemplateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
