// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// StorageService is an autogenerated mock type for the StorageService type
type StorageService struct {
	mock.Mock
}

// DeleteFile provides a mock function with given fields: ctx, fileURL
func (_m *StorageService) DeleteFile(ctx context.Context, fileURL string) error {
	ret := _m.Called(ctx, fileURL)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, fileURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadFile provides a mock function with given fields: ctx, file, folder, fileName
func (_m *StorageService) UploadFile(ctx context.Context, file *multipart.FileHeader, folder string, fileName string) (string, error) {
	ret := _m.Called(ctx, file, folder, fileName)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string, string) (string, error)); ok {
		return rf(ctx, file, folder, fileName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string, string) string); ok {
		r0 = rf(ctx, file, folder, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader, string, string) error); ok {
		r1 = rf(ctx, file, folder, fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
