// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// UploadUsecase is an autogenerated mock type for the UploadUsecase type
type UploadUsecase struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: ctx, file, folder
func (_m *UploadUsecase) UploadImage(ctx context.Context, file *multipart.FileHeader, folder string) (string, error) {
	ret := _m.Called(ctx, file, folder)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string) (string, error)); ok {
		return rf(ctx, file, folder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string) string); ok {
		r0 = rf(ctx, file, folder)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader, string) error); ok {
		r1 = rf(ctx, file, folder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUploadUsecase creates a new instance of UploadUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadUsecase {
	mock := &UploadUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
