// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// WorkLogUsecase is an autogenerated mock type for the WorkLogUsecase type
type WorkLogUsecase struct {
	mock.Mock
}

// CreateWorkLog provides a mock function with given fields: ctx, input
func (_m *WorkLogUsecase) CreateWorkLog(ctx context.Context, input domain.WorkLogCreateInput) (*domain.WorkLog, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkLog")
	}

	var r0 *domain.WorkLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.WorkLogCreateInput) (*domain.WorkLog, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.WorkLogCreateInput) *domain.WorkLog); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.WorkLogCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWorkLog provides a mock function with given fields: ctx, id
func (_m *WorkLogUsecase) DeleteWorkLog(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWorkLog provides a mock function with given fields: ctx, id
func (_m *WorkLogUsecase) GetWorkLog(ctx context.Context, id string) (*domain.WorkLog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkLog")
	}

	var r0 *domain.WorkLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.WorkLog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.WorkLog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkLogs provides a mock function with given fields: ctx, query, filter
func (_m *WorkLogUsecase) ListWorkLogs(ctx context.Context, query domain.PaginationQuery, filter domain.WorkLogFilter) ([]domain.WorkLog, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, query, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkLogs")
	}

	var r0 []domain.WorkLog
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.WorkLogFilter) ([]domain.WorkLog, domain.PaginationMeta, error)); ok {
		return rf(ctx, query, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.WorkLogFilter) []domain.WorkLog); ok {
		r0 = rf(ctx, query, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WorkLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery, domain.WorkLogFilter) domain.PaginationMeta); ok {
		r1 = rf(ctx, query, filter)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery, domain.WorkLogFilter) error); ok {
		r2 = rf(ctx, query, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateWorkLog provides a mock function with given fields: ctx, id, input
func (_m *WorkLogUsecase) UpdateWorkLog(ctx context.Context, id string, input domain.WorkLogUpdateInput) (*domain.WorkLog, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkLog")
	}

	var r0 *domain.WorkLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.WorkLogUpdateInput) (*domain.WorkLog, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.WorkLogUpdateInput) *domain.WorkLog); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.WorkLogUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorkLogUsecase creates a new instance of WorkLogUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkLogUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkLogUsecase {
	mock := &WorkLogUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
