// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// WorkerUsecase is an autogenerated mock type for the WorkerUsecase type
type WorkerUsecase struct {
	mock.Mock
}

// CreateWorker provides a mock function with given fields: ctx, input
func (_m *WorkerUsecase) CreateWorker(ctx context.Context, input domain.WorkerCreateInput) (*domain.Worker, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorker")
	}

	var r0 *domain.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.WorkerCreateInput) (*domain.Worker, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.WorkerCreateInput) *domain.Worker); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.WorkerCreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWorker provides a mock function with given fields: ctx, id
func (_m *WorkerUsecase) DeleteWorker(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWorker provides a mock function with given fields: ctx, id
func (_m *WorkerUsecase) GetWorker(ctx context.Context, id string) (*domain.Worker, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWorker")
	}

	var r0 *domain.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Worker, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Worker); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkers provides a mock function with given fields: ctx, query, filter
func (_m *WorkerUsecase) ListWorkers(ctx context.Context, query domain.PaginationQuery, filter domain.WorkerFilter) ([]domain.Worker, domain.PaginationMeta, error) {
	ret := _m.Called(ctx, query, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkers")
	}

	var r0 []domain.Worker
	var r1 domain.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.WorkerFilter) ([]domain.Worker, domain.PaginationMeta, error)); ok {
		return rf(ctx, query, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaginationQuery, domain.WorkerFilter) []domain.Worker); ok {
		r0 = rf(ctx, query, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaginationQuery, domain.WorkerFilter) domain.PaginationMeta); ok {
		r1 = rf(ctx, query, filter)
	} else {
		r1 = ret.Get(1).(domain.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaginationQuery, domain.WorkerFilter) error); ok {
		r2 = rf(ctx, query, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateWorker provides a mock function with given fields: ctx, id, input
func (_m *WorkerUsecase) UpdateWorker(ctx context.Context, id string, input domain.WorkerUpdateInput) (*domain.Worker, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorker")
	}

	var r0 *domain.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.WorkerUpdateInput) (*domain.Worker, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.WorkerUpdateInput) *domain.Worker); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.WorkerUpdateInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorkerUsecase creates a new instance of WorkerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerUsecase {
	mock := &WorkerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
