// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// WorkerRepository is an autogenerated mock type for the WorkerRepository type
type WorkerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, worker
func (_m *WorkerRepository) Create(ctx context.Context, worker *domain.Worker) error {
	ret := _m.Called(ctx, worker)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Worker) error); ok {
		r0 = rf(ctx, worker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WorkerRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, filter, limit, offset
func (_m *WorkerRepository) Fetch(ctx context.Context, filter domain.WorkerFilter, limit int, offset int) ([]domain.Worker, int64, error) {
	ret := _m.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Worker
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.WorkerFilter, int, int) ([]domain.Worker, int64, error)); ok {
		return rf(ctx, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.WorkerFilter, int, int) []domain.Worker); ok {
		r0 = rf(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.WorkerFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.WorkerFilter, int, int) error); ok {
		r2 = rf(ctx, filter, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *WorkerRepository) GetByID(ctx context.Context, id string) (*domain.Worker, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Worker, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Worker); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, worker
func (_m *WorkerRepository) Update(ctx context.Context, worker *domain.Worker) error {
	ret := _m.Called(ctx, worker)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Worker) error); ok {
		r0 = rf(ctx, worker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkerRepository creates a new instance of WorkerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerRepository {
	mock := &WorkerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
