// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/sikon-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// WorkLogRepository is an autogenerated mock type for the WorkLogRepository type
type WorkLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, log
func (_m *WorkLogRepository) Create(ctx context.Context, log *domain.WorkLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WorkLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatch provides a mock function with given fields: ctx, logs
func (_m *WorkLogRepository) CreateBatch(ctx context.Context, logs []domain.WorkLog) error {
	ret := _m.Called(ctx, logs)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.WorkLog) error); ok {
		r0 = rf(ctx, logs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WorkLogRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, filter, limit, offset
func (_m *WorkLogRepository) Fetch(ctx context.Context, filter domain.WorkLogFilter, limit int, offset int) ([]domain.WorkLog, int64, error) {
	ret := _m.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.WorkLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.WorkLogFilter, int, int) ([]domain.WorkLog, int64, error)); ok {
		return rf(ctx, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.WorkLogFilter, int, int) []domain.WorkLog); ok {
		r0 = rf(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WorkLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.WorkLogFilter, int, int) int64); ok {
		r1 = rf(ctx, filter, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.WorkLogFilter, int, int) error); ok {
		r2 = rf(ctx, filter, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *WorkLogRepository) GetByID(ctx context.Context, id string) (*domain.WorkLog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.WorkLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.WorkLog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.WorkLog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalCostByBatchPO provides a mock function with given fields: ctx, batchPoID
func (_m *WorkLogRepository) GetTotalCostByBatchPO(ctx context.Context, batchPoID string) (float64, error) {
	ret := _m.Called(ctx, batchPoID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalCostByBatchPO")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, batchPoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, batchPoID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, batchPoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalCostByOrder provides a mock function with given fields: ctx, orderID
func (_m *WorkLogRepository) GetTotalCostByOrder(ctx context.Context, orderID string) (float64, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalCostByOrder")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalQtyByOrderAndJobType provides a mock function with given fields: ctx, orderID, jobType, excludeLogID
func (_m *WorkLogRepository) GetTotalQtyByOrderAndJobType(ctx context.Context, orderID string, jobType domain.JobType, excludeLogID string) (int, error) {
	ret := _m.Called(ctx, orderID, jobType, excludeLogID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalQtyByOrderAndJobType")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.JobType, string) (int, error)); ok {
		return rf(ctx, orderID, jobType, excludeLogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.JobType, string) int); ok {
		r0 = rf(ctx, orderID, jobType, excludeLogID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.JobType, string) error); ok {
		r1 = rf(ctx, orderID, jobType, excludeLogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, log
func (_m *WorkLogRepository) Update(ctx context.Context, log *domain.WorkLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WorkLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkLogRepository creates a new instance of WorkLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkLogRepository {
	mock := &WorkLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
